service: mastermnd-python-lab
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  evenOrOdd:
    handler: handler.evenOrOdd
    events:
      - http:
          path: evenOrOdd
          method: get
  squareAnyNum:
    handler: handler.squareAnyNum
    events:
      - http:
          path: squareNum
          method: get
