---
- hosts: webservers
  gather_facts: yes
  become: yes
  tasks:
  - name: Install Nginx
    apt: pkg=nginx state=present update_cache=yes
    notify:
    - restart nginx
  - name: Enable Nginx during boot
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
